// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:newsweather_app/main.dart';

// Future<void> main() async {
//   WidgetsFlutterBinding.ensureInitialized();

//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );

//   runApp(MyApp());
// }

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBePsA6u8RGUoYG2wJMhWmLWDO3xKCDGE8',
    appId: '1:605410622339:web:659dc1fe12ff55ac7c54b6',
    messagingSenderId: '605410622339',
    projectId: 'news-weatherapp',
    authDomain: 'news-weatherapp.firebaseapp.com',
    storageBucket: 'news-weatherapp.firebasestorage.app',
    measurementId: 'G-DEXJWW3EBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-tyot3fCuiRvgsFFnYTAKKd9YDHSqBI',
    appId: '1:605410622339:android:1fec9adea1f7ad747c54b6',
    messagingSenderId: '605410622339',
    projectId: 'news-weatherapp',
    storageBucket: 'news-weatherapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApCksX0nfsuHhj-HVBGcolxwzwdE7dhsA',
    appId: '1:605410622339:ios:0763b00fae4e2b0e7c54b6',
    messagingSenderId: '605410622339',
    projectId: 'news-weatherapp',
    storageBucket: 'news-weatherapp.firebasestorage.app',
    iosBundleId: 'com.example.newsweatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApCksX0nfsuHhj-HVBGcolxwzwdE7dhsA',
    appId: '1:605410622339:ios:0763b00fae4e2b0e7c54b6',
    messagingSenderId: '605410622339',
    projectId: 'news-weatherapp',
    storageBucket: 'news-weatherapp.firebasestorage.app',
    iosBundleId: 'com.example.newsweatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBePsA6u8RGUoYG2wJMhWmLWDO3xKCDGE8',
    appId: '1:605410622339:web:01be762ac34fc6777c54b6',
    messagingSenderId: '605410622339',
    projectId: 'news-weatherapp',
    authDomain: 'news-weatherapp.firebaseapp.com',
    storageBucket: 'news-weatherapp.firebasestorage.app',
    measurementId: 'G-L4YB2D6DGJ',
  );
}
